# Generated by Django 4.1.3 on 2022-11-26 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RegEntrada', models.CharField(max_length=150, verbose_name='Nombre del Pedido')),
                ('Muestra', models.CharField(choices=[('Fisica', 'Fisica'), ('Digital', 'Digital'), ('Domi', 'Domi'), ('Fotografica', 'Fotografica')], max_length=150, verbose_name='Tipo de Muestra')),
                ('FotoPedido', models.ImageField(upload_to='static/pedidos/', verbose_name='Imagen del Pedido')),
                ('FechaPed', models.DateField(verbose_name='Fecha del Pedido')),
                ('FechaElab', models.DateField(verbose_name='Fecha del Recepcion')),
                ('Indicaciones', models.TextField(blank=True, null=True, verbose_name='Indicaciones')),
                ('Cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Cliente_OP', to='cliente.perfil', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'OPedido',
                'verbose_name_plural': 'OPedidos',
                'db_table': 'OPedidos',
                'managed': True,
            },
        ),
    ]
