# Generated by Django 4.1.3 on 2022-11-24 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_opedido_cliente_alter_opedido_indicaciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opedido',
            name='Cliente',
        ),
    ]
