# Generated by Django 4.1.3 on 2022-11-24 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
        ('pedidos', '0003_remove_opedido_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='opedido',
            name='Cliente',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Cliente_OP', to='cliente.perfil', verbose_name='Cliente'),
            preserve_default=False,
        ),
    ]
