# Generated by Django 4.1.3 on 2022-11-29 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_alter_opedido_indicaciones'),
        ('pedidos', '0004_opedido_cliente'),
    ]

    operations = [
    ]
