# Generated by Django 4.1.3 on 2022-11-26 03:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreCliente', models.CharField(max_length=150, verbose_name='Nombre del Cliente')),
                ('Abreviatura', models.CharField(max_length=10, verbose_name='Abreviatura')),
                ('imgPerfil', models.ImageField(upload_to='static/cliente/perfil', verbose_name='Imagen del Perfil')),
                ('UsuarioCliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario en el Sistema')),
            ],
            options={
                'verbose_name': 'perfil',
                'verbose_name_plural': 'perfiles',
                'db_table': 'perfil',
                'managed': True,
            },
        ),
    ]
