# Generated by Django 4.1.3 on 2022-11-29 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='imgPerfil',
            field=models.ImageField(blank=True, null=True, upload_to='static/cliente/perfil', verbose_name='Imagen del Perfil'),
        ),
    ]
