# Generated by Django 4.1.3 on 2022-11-29 03:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedidos', '0002_alter_opedido_indicaciones'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('almacen', '0001_initial'),
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Folio', models.CharField(max_length=15, verbose_name='Folio de Producción No')),
                ('FolioCliente', models.CharField(max_length=10, verbose_name='Folio de Cliente')),
                ('NombreTrabajo', models.CharField(max_length=250, verbose_name='Nombre del Trabajo')),
                ('FechaElaboracion', models.DateField(verbose_name='Fecha de Elaboración')),
                ('TipoTrabajo', models.CharField(choices=[('Nuevo', 'Nuevo'), ('Resurtido', 'Resurtido'), ('Reposición', 'Reposición')], max_length=15, verbose_name='Tipo de Orde')),
                ('TipoGrosor', models.CharField(choices=[('Sencillo', 'Sencillo'), ('Empalamado', 'Empalamado'), ('Doble Vista', 'Doble Vista')], max_length=15, verbose_name='Tipo de Orde')),
                ('CantidadPapel', models.SmallIntegerField(verbose_name='Tamaños Asignados')),
                ('CantidadMerma', models.SmallIntegerField(verbose_name='Merma Asignada')),
                ('PedidoCantidad', models.PositiveIntegerField(verbose_name='Cantidad Solicitada')),
                ('Observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('Cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Cliente', to='cliente.perfil', verbose_name='Cliente')),
                ('ElaboradoPor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Elaborado Por:')),
                ('HotStamping', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='HotStamping', to='almacen.foil', verbose_name='Hot Stamping')),
                ('ImpresionFrente', models.ManyToManyField(blank=True, related_name='ImpresionFrente', to='almacen.tinta', verbose_name='Tintas Frente')),
                ('ImpresionReverso', models.ManyToManyField(blank=True, related_name='ImpresionReverso', to='almacen.tinta', verbose_name='Tintas Reverso')),
                ('OrdenPedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Orden_Pedido', to='pedidos.opedido', verbose_name='Pedido Original')),
                ('TipoBarniz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TipoBarniz', to='almacen.barniz', verbose_name='Tipo de barniz')),
                ('TipoBotado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Botado', to='almacen.laser', verbose_name='Botado')),
                ('TipoClisse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TipoClisse', to='almacen.clisse', verbose_name='Tipo de Clisse')),
                ('TipoLaminado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TipoLaminado', to='almacen.laminado', verbose_name='Tipo de Laminado')),
                ('TipoPapel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Papel', to='almacen.papel', verbose_name='Papel')),
                ('TipoSuaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Suaje', to='almacen.suaje', verbose_name='Suaje')),
            ],
            options={
                'verbose_name': 'OrdenProduccion',
                'verbose_name_plural': 'OrdenProduccions',
                'db_table': 'OrdenProduccion',
                'managed': True,
            },
        ),
    ]
