# Generated by Django 4.1.3 on 2022-11-29 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produccion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalidaMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Paquete1', models.IntegerField(verbose_name='Paquete 1')),
                ('Paquete2', models.IntegerField(blank=True, null=True, verbose_name='Paquete 2')),
                ('Paquete3', models.IntegerField(blank=True, null=True, verbose_name='Paquete 3')),
                ('Paquete4', models.IntegerField(blank=True, null=True, verbose_name='Paquete 4')),
                ('Paquete5', models.IntegerField(blank=True, null=True, verbose_name='Paquete 5')),
                ('Paquete6', models.IntegerField(blank=True, null=True, verbose_name='Paquete 6')),
                ('Paquete7', models.IntegerField(blank=True, null=True, verbose_name='Paquete 7')),
                ('Paquete8', models.IntegerField(blank=True, null=True, verbose_name='Paquete 8')),
                ('OProduccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion.ordenproduccion', verbose_name='Orde de Produccion')),
            ],
            options={
                'verbose_name': 'SalidaMaterial',
                'verbose_name_plural': 'SalidaMateriales',
                'db_table': 'SalidaMaterial',
                'managed': True,
            },
        ),
    ]
