# Generated by Django 4.1.3 on 2022-11-29 03:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Envios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaPreparacion', models.CharField(choices=[(datetime.date(2022, 11, 28), 48)], max_length=250, verbose_name='Fecha de Preparacion')),
                ('CostoPlacas', models.SmallIntegerField(verbose_name='Costo Placas')),
                ('TotalPlacas', models.SmallIntegerField(verbose_name='Placas Totales')),
                ('FechaPlacas', models.DateField(verbose_name='Fecha de Preparación Placas')),
                ('FechaEnvioPlacas', models.DateField(verbose_name='Fecha de Envio Placas')),
                ('Serigrafia', models.SmallIntegerField(verbose_name='Cantidad de Albanenes')),
                ('FechaSerigrafia', models.DateField(verbose_name='Fecha de Preparación Alabanenes')),
                ('FechaEnvioSeri', models.DateField(verbose_name='Fecha de Envio Albanene')),
                ('CostoClisse', models.SmallIntegerField(verbose_name='Costo Clisse')),
                ('FechaClisse', models.DateField(verbose_name='Fecha de Preparación Clisse')),
                ('FechaEnvioClisse', models.DateField(verbose_name='Fecha de Envio Clisse')),
                ('CostoSuaje', models.SmallIntegerField(verbose_name='Costo Suaje')),
                ('FechaSuaje', models.DateField(verbose_name='Fecha de Preparación Suaje')),
                ('FechaEnvioSuaje', models.DateField(verbose_name='Fecha de Envio Suaje')),
                ('CostoLaser', models.SmallIntegerField(verbose_name='Costo Laser')),
                ('FechaLaser', models.DateField(verbose_name='Fecha de Preparación Laser')),
                ('FechaEnvioLaser', models.DateField(verbose_name='Fecha de Envio Laser')),
            ],
            options={
                'verbose_name': 'SalidasProvedor',
                'verbose_name_plural': 'SalidasProvedores',
                'db_table': 'SalidasProvedor',
                'managed': True,
            },
        ),
    ]
