# Generated by Django 4.1.3 on 2022-11-29 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bitacora', '0001_initial'),
        ('produccion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='envios',
            name='OProduct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OrdenProducto', to='produccion.ordenproduccion', verbose_name='Orden de Producción'),
        ),
    ]
