# Generated by Django 4.1.3 on 2022-11-29 04:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitacora', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envios',
            name='FechaPreparacion',
            field=models.CharField(choices=[(datetime.date(2022, 11, 20), 46), (datetime.date(2022, 11, 28), 48), (datetime.date(2022, 12, 6), 49)], max_length=250, verbose_name='Semana de Produccion'),
        ),
    ]
