# Generated by Django 4.1.3 on 2022-11-29 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitacora', '0003_alter_envios_fechapreparacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envios',
            name='CostoClisse',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Costo Clisse'),
        ),
        migrations.AlterField(
            model_name='envios',
            name='CostoLaser',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Costo Laser'),
        ),
        migrations.AlterField(
            model_name='envios',
            name='CostoPlacas',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Costo Placas'),
        ),
        migrations.AlterField(
            model_name='envios',
            name='CostoSuaje',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Costo Suaje'),
        ),
        migrations.AlterField(
            model_name='envios',
            name='FechaClisse',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Preparación Clisse'),
        ),
        migrations.AlterField(
            model_name='envios',
            name='FechaEnvioClisse',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Envio Clisse'),
        ),
        migrations.AlterField(
            model_name='envios',
            name='FechaEnvioLaser',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Envio Laser'),
        ),
        migrations.AlterField(
            model_name='envios',
            name='FechaEnvioPlacas',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Envio Placas'),
        ),
        migrations.AlterField(
            model_name='envios',
            name='FechaEnvioSeri',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Envio Albanene'),
        ),
        migrations.AlterField(
            model_name='envios',
            name='FechaEnvioSuaje',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Envio Suaje'),
        ),
        migrations.AlterField(
            model_name='envios',
            name='FechaLaser',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Preparación Laser'),
        ),
        migrations.AlterField(
            model_name='envios',
            name='FechaPlacas',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Preparación Placas'),
        ),
        migrations.AlterField(
            model_name='envios',
            name='FechaSerigrafia',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Preparación Alabanenes'),
        ),
        migrations.AlterField(
            model_name='envios',
            name='FechaSuaje',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Preparación Suaje'),
        ),
        migrations.AlterField(
            model_name='envios',
            name='Serigrafia',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Cantidad de Albanenes'),
        ),
        migrations.AlterField(
            model_name='envios',
            name='TotalPlacas',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Placas Totales'),
        ),
    ]
