# Generated by Django 4.1.3 on 2022-11-29 15:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitacora', '0004_alter_envios_costoclisse_alter_envios_costolaser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envios',
            name='FechaPreparacion',
            field=models.CharField(choices=[(datetime.date(2022, 11, 21), 47), (datetime.date(2022, 11, 29), 48), (datetime.date(2022, 12, 7), 49)], max_length=250, verbose_name='Semana de Produccion'),
        ),
    ]
