# Generated by Django 4.1.3 on 2022-11-29 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitacora', '0005_alter_envios_fechapreparacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='envios',
            name='ReciboClisse',
            field=models.BooleanField(blank=True, null=True, verbose_name='Clisse Recibido'),
        ),
        migrations.AddField(
            model_name='envios',
            name='ReciboLaser',
            field=models.BooleanField(blank=True, null=True, verbose_name='Corte Laser Recibido'),
        ),
        migrations.AddField(
            model_name='envios',
            name='ReciboPlacas',
            field=models.BooleanField(blank=True, null=True, verbose_name='Placas Recibidas'),
        ),
        migrations.AddField(
            model_name='envios',
            name='ReciboSerigrafia',
            field=models.BooleanField(blank=True, null=True, verbose_name='Albanene Recibido'),
        ),
        migrations.AddField(
            model_name='envios',
            name='ReciboSuaje',
            field=models.BooleanField(blank=True, null=True, verbose_name='Suaje Recibido'),
        ),
    ]
