# Generated by Django 4.1.3 on 2022-12-14 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitacora', '0007_alter_envios_fechapreparacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envios',
            name='FechaPreparacion',
            field=models.CharField(choices=[('2022-12-06', '49'), ('2022-12-14', 50), ('2022-12-22', '51')], help_text='La fecha puede ser este dia, una o dos semanas antes o una o dos semanas despues', max_length=250, verbose_name='Semana de Produccion'),
        ),
    ]
